// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/producer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	User          string                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSearchRequest) Reset() {
	*x = SendSearchRequest{}
	mi := &file_proto_producer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSearchRequest) ProtoMessage() {}

func (x *SendSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSearchRequest.ProtoReflect.Descriptor instead.
func (*SendSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_producer_proto_rawDescGZIP(), []int{0}
}

func (x *SendSearchRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *SendSearchRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *SendSearchRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type SendSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendSearchResponse) Reset() {
	*x = SendSearchResponse{}
	mi := &file_proto_producer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendSearchResponse) ProtoMessage() {}

func (x *SendSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_producer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendSearchResponse.ProtoReflect.Descriptor instead.
func (*SendSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_producer_proto_rawDescGZIP(), []int{1}
}

func (x *SendSearchResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendSearchResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_producer_proto protoreflect.FileDescriptor

const file_proto_producer_proto_rawDesc = "" +
	"\n" +
	"\x14proto/producer.proto\x12\bproducer\x1a\x1fgoogle/protobuf/timestamp.proto\"y\n" +
	"\x11SendSearchRequest\x12\x16\n" +
	"\x06search\x18\x01 \x01(\tR\x06search\x12\x12\n" +
	"\x04user\x18\x02 \x01(\tR\x04user\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"H\n" +
	"\x12SendSearchResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2S\n" +
	"\bProducer\x12G\n" +
	"\n" +
	"SendSearch\x12\x1b.producer.SendSearchRequest\x1a\x1c.producer.SendSearchResponseB8Z6github.com/middelmatigheid/top-searches/proto;protob\x06proto3"

var (
	file_proto_producer_proto_rawDescOnce sync.Once
	file_proto_producer_proto_rawDescData []byte
)

func file_proto_producer_proto_rawDescGZIP() []byte {
	file_proto_producer_proto_rawDescOnce.Do(func() {
		file_proto_producer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_producer_proto_rawDesc), len(file_proto_producer_proto_rawDesc)))
	})
	return file_proto_producer_proto_rawDescData
}

var file_proto_producer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_producer_proto_goTypes = []any{
	(*SendSearchRequest)(nil),     // 0: producer.SendSearchRequest
	(*SendSearchResponse)(nil),    // 1: producer.SendSearchResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_proto_producer_proto_depIdxs = []int32{
	2, // 0: producer.SendSearchRequest.timestamp:type_name -> google.protobuf.Timestamp
	0, // 1: producer.Producer.SendSearch:input_type -> producer.SendSearchRequest
	1, // 2: producer.Producer.SendSearch:output_type -> producer.SendSearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_producer_proto_init() }
func file_proto_producer_proto_init() {
	if File_proto_producer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_producer_proto_rawDesc), len(file_proto_producer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_producer_proto_goTypes,
		DependencyIndexes: file_proto_producer_proto_depIdxs,
		MessageInfos:      file_proto_producer_proto_msgTypes,
	}.Build()
	File_proto_producer_proto = out.File
	file_proto_producer_proto_goTypes = nil
	file_proto_producer_proto_depIdxs = nil
}
