// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/searches.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Searches_GetTopN_FullMethodName = "/searches.Searches/GetTopN"
)

// SearchesClient is the client API for Searches service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for managing top searches
type SearchesClient interface {
	// Get N top searches
	GetTopN(ctx context.Context, in *GetTopNRequest, opts ...grpc.CallOption) (*GetTopNResponse, error)
}

type searchesClient struct {
	cc grpc.ClientConnInterface
}

func NewSearchesClient(cc grpc.ClientConnInterface) SearchesClient {
	return &searchesClient{cc}
}

func (c *searchesClient) GetTopN(ctx context.Context, in *GetTopNRequest, opts ...grpc.CallOption) (*GetTopNResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTopNResponse)
	err := c.cc.Invoke(ctx, Searches_GetTopN_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SearchesServer is the server API for Searches service.
// All implementations must embed UnimplementedSearchesServer
// for forward compatibility.
//
// Service for managing top searches
type SearchesServer interface {
	// Get N top searches
	GetTopN(context.Context, *GetTopNRequest) (*GetTopNResponse, error)
	mustEmbedUnimplementedSearchesServer()
}

// UnimplementedSearchesServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSearchesServer struct{}

func (UnimplementedSearchesServer) GetTopN(context.Context, *GetTopNRequest) (*GetTopNResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTopN not implemented")
}
func (UnimplementedSearchesServer) mustEmbedUnimplementedSearchesServer() {}
func (UnimplementedSearchesServer) testEmbeddedByValue()                  {}

// UnsafeSearchesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SearchesServer will
// result in compilation errors.
type UnsafeSearchesServer interface {
	mustEmbedUnimplementedSearchesServer()
}

func RegisterSearchesServer(s grpc.ServiceRegistrar, srv SearchesServer) {
	// If the following call panics, it indicates UnimplementedSearchesServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Searches_ServiceDesc, srv)
}

func _Searches_GetTopN_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTopNRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchesServer).GetTopN(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Searches_GetTopN_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchesServer).GetTopN(ctx, req.(*GetTopNRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Searches_ServiceDesc is the grpc.ServiceDesc for Searches service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Searches_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "searches.Searches",
	HandlerType: (*SearchesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTopN",
			Handler:    _Searches_GetTopN_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/searches.proto",
}
