// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/stoplist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_proto_stoplist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stoplist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_proto_stoplist_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_proto_stoplist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stoplist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_proto_stoplist_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRequest) Reset() {
	*x = RemoveRequest{}
	mi := &file_proto_stoplist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRequest) ProtoMessage() {}

func (x *RemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stoplist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRequest.ProtoReflect.Descriptor instead.
func (*RemoveRequest) Descriptor() ([]byte, []int) {
	return file_proto_stoplist_proto_rawDescGZIP(), []int{2}
}

func (x *RemoveRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type RemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveResponse) Reset() {
	*x = RemoveResponse{}
	mi := &file_proto_stoplist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveResponse) ProtoMessage() {}

func (x *RemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stoplist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveResponse.ProtoReflect.Descriptor instead.
func (*RemoveResponse) Descriptor() ([]byte, []int) {
	return file_proto_stoplist_proto_rawDescGZIP(), []int{3}
}

func (x *RemoveResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStoplistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoplistRequest) Reset() {
	*x = GetStoplistRequest{}
	mi := &file_proto_stoplist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoplistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoplistRequest) ProtoMessage() {}

func (x *GetStoplistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stoplist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoplistRequest.ProtoReflect.Descriptor instead.
func (*GetStoplistRequest) Descriptor() ([]byte, []int) {
	return file_proto_stoplist_proto_rawDescGZIP(), []int{4}
}

type GetStoplistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Words         []string               `protobuf:"bytes,1,rep,name=words,proto3" json:"words,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStoplistResponse) Reset() {
	*x = GetStoplistResponse{}
	mi := &file_proto_stoplist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStoplistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStoplistResponse) ProtoMessage() {}

func (x *GetStoplistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stoplist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStoplistResponse.ProtoReflect.Descriptor instead.
func (*GetStoplistResponse) Descriptor() ([]byte, []int) {
	return file_proto_stoplist_proto_rawDescGZIP(), []int{5}
}

func (x *GetStoplistResponse) GetWords() []string {
	if x != nil {
		return x.Words
	}
	return nil
}

type ContainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Word          string                 `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainsRequest) Reset() {
	*x = ContainsRequest{}
	mi := &file_proto_stoplist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsRequest) ProtoMessage() {}

func (x *ContainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stoplist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsRequest.ProtoReflect.Descriptor instead.
func (*ContainsRequest) Descriptor() ([]byte, []int) {
	return file_proto_stoplist_proto_rawDescGZIP(), []int{6}
}

func (x *ContainsRequest) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

type ContainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contains      bool                   `protobuf:"varint,1,opt,name=contains,proto3" json:"contains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainsResponse) Reset() {
	*x = ContainsResponse{}
	mi := &file_proto_stoplist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainsResponse) ProtoMessage() {}

func (x *ContainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stoplist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainsResponse.ProtoReflect.Descriptor instead.
func (*ContainsResponse) Descriptor() ([]byte, []int) {
	return file_proto_stoplist_proto_rawDescGZIP(), []int{7}
}

func (x *ContainsResponse) GetContains() bool {
	if x != nil {
		return x.Contains
	}
	return false
}

var File_proto_stoplist_proto protoreflect.FileDescriptor

const file_proto_stoplist_proto_rawDesc = "" +
	"\n" +
	"\x14proto/stoplist.proto\x12\bstoplist\" \n" +
	"\n" +
	"AddRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"A\n" +
	"\vAddResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"#\n" +
	"\rRemoveRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\"D\n" +
	"\x0eRemoveResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12GetStoplistRequest\"+\n" +
	"\x13GetStoplistResponse\x12\x14\n" +
	"\x05words\x18\x01 \x03(\tR\x05words\"%\n" +
	"\x0fContainsRequest\x12\x12\n" +
	"\x04word\x18\x01 \x01(\tR\x04word\".\n" +
	"\x10ContainsResponse\x12\x1a\n" +
	"\bcontains\x18\x01 \x01(\bR\bcontains2\x8a\x02\n" +
	"\bStoplist\x122\n" +
	"\x03Add\x12\x14.stoplist.AddRequest\x1a\x15.stoplist.AddResponse\x12;\n" +
	"\x06Remove\x12\x17.stoplist.RemoveRequest\x1a\x18.stoplist.RemoveResponse\x12J\n" +
	"\vGetStoplist\x12\x1c.stoplist.GetStoplistRequest\x1a\x1d.stoplist.GetStoplistResponse\x12A\n" +
	"\bContains\x12\x19.stoplist.ContainsRequest\x1a\x1a.stoplist.ContainsResponseB8Z6github.com/middelmatigheid/top-searches/proto;protob\x06proto3"

var (
	file_proto_stoplist_proto_rawDescOnce sync.Once
	file_proto_stoplist_proto_rawDescData []byte
)

func file_proto_stoplist_proto_rawDescGZIP() []byte {
	file_proto_stoplist_proto_rawDescOnce.Do(func() {
		file_proto_stoplist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stoplist_proto_rawDesc), len(file_proto_stoplist_proto_rawDesc)))
	})
	return file_proto_stoplist_proto_rawDescData
}

var file_proto_stoplist_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_stoplist_proto_goTypes = []any{
	(*AddRequest)(nil),          // 0: stoplist.AddRequest
	(*AddResponse)(nil),         // 1: stoplist.AddResponse
	(*RemoveRequest)(nil),       // 2: stoplist.RemoveRequest
	(*RemoveResponse)(nil),      // 3: stoplist.RemoveResponse
	(*GetStoplistRequest)(nil),  // 4: stoplist.GetStoplistRequest
	(*GetStoplistResponse)(nil), // 5: stoplist.GetStoplistResponse
	(*ContainsRequest)(nil),     // 6: stoplist.ContainsRequest
	(*ContainsResponse)(nil),    // 7: stoplist.ContainsResponse
}
var file_proto_stoplist_proto_depIdxs = []int32{
	0, // 0: stoplist.Stoplist.Add:input_type -> stoplist.AddRequest
	2, // 1: stoplist.Stoplist.Remove:input_type -> stoplist.RemoveRequest
	4, // 2: stoplist.Stoplist.GetStoplist:input_type -> stoplist.GetStoplistRequest
	6, // 3: stoplist.Stoplist.Contains:input_type -> stoplist.ContainsRequest
	1, // 4: stoplist.Stoplist.Add:output_type -> stoplist.AddResponse
	3, // 5: stoplist.Stoplist.Remove:output_type -> stoplist.RemoveResponse
	5, // 6: stoplist.Stoplist.GetStoplist:output_type -> stoplist.GetStoplistResponse
	7, // 7: stoplist.Stoplist.Contains:output_type -> stoplist.ContainsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_stoplist_proto_init() }
func file_proto_stoplist_proto_init() {
	if File_proto_stoplist_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stoplist_proto_rawDesc), len(file_proto_stoplist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stoplist_proto_goTypes,
		DependencyIndexes: file_proto_stoplist_proto_depIdxs,
		MessageInfos:      file_proto_stoplist_proto_msgTypes,
	}.Build()
	File_proto_stoplist_proto = out.File
	file_proto_stoplist_proto_goTypes = nil
	file_proto_stoplist_proto_depIdxs = nil
}
