// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/stoplist.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Stoplist_Add_FullMethodName         = "/stoplist.Stoplist/Add"
	Stoplist_Remove_FullMethodName      = "/stoplist.Stoplist/Remove"
	Stoplist_GetStoplist_FullMethodName = "/stoplist.Stoplist/GetStoplist"
	Stoplist_Contains_FullMethodName    = "/stoplist.Stoplist/Contains"
)

// StoplistClient is the client API for Stoplist service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for managing stoplist
type StoplistClient interface {
	// Add new word to the stoplist
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	// Remove word from the stoplist
	Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error)
	// Get stoplist
	GetStoplist(ctx context.Context, in *GetStoplistRequest, opts ...grpc.CallOption) (*GetStoplistResponse, error)
	// Check if the stoplist contains a word
	Contains(ctx context.Context, in *ContainsRequest, opts ...grpc.CallOption) (*ContainsResponse, error)
}

type stoplistClient struct {
	cc grpc.ClientConnInterface
}

func NewStoplistClient(cc grpc.ClientConnInterface) StoplistClient {
	return &stoplistClient{cc}
}

func (c *stoplistClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, Stoplist_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoplistClient) Remove(ctx context.Context, in *RemoveRequest, opts ...grpc.CallOption) (*RemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveResponse)
	err := c.cc.Invoke(ctx, Stoplist_Remove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoplistClient) GetStoplist(ctx context.Context, in *GetStoplistRequest, opts ...grpc.CallOption) (*GetStoplistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStoplistResponse)
	err := c.cc.Invoke(ctx, Stoplist_GetStoplist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stoplistClient) Contains(ctx context.Context, in *ContainsRequest, opts ...grpc.CallOption) (*ContainsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContainsResponse)
	err := c.cc.Invoke(ctx, Stoplist_Contains_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoplistServer is the server API for Stoplist service.
// All implementations must embed UnimplementedStoplistServer
// for forward compatibility.
//
// Service for managing stoplist
type StoplistServer interface {
	// Add new word to the stoplist
	Add(context.Context, *AddRequest) (*AddResponse, error)
	// Remove word from the stoplist
	Remove(context.Context, *RemoveRequest) (*RemoveResponse, error)
	// Get stoplist
	GetStoplist(context.Context, *GetStoplistRequest) (*GetStoplistResponse, error)
	// Check if the stoplist contains a word
	Contains(context.Context, *ContainsRequest) (*ContainsResponse, error)
	mustEmbedUnimplementedStoplistServer()
}

// UnimplementedStoplistServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoplistServer struct{}

func (UnimplementedStoplistServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedStoplistServer) Remove(context.Context, *RemoveRequest) (*RemoveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Remove not implemented")
}
func (UnimplementedStoplistServer) GetStoplist(context.Context, *GetStoplistRequest) (*GetStoplistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStoplist not implemented")
}
func (UnimplementedStoplistServer) Contains(context.Context, *ContainsRequest) (*ContainsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Contains not implemented")
}
func (UnimplementedStoplistServer) mustEmbedUnimplementedStoplistServer() {}
func (UnimplementedStoplistServer) testEmbeddedByValue()                  {}

// UnsafeStoplistServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoplistServer will
// result in compilation errors.
type UnsafeStoplistServer interface {
	mustEmbedUnimplementedStoplistServer()
}

func RegisterStoplistServer(s grpc.ServiceRegistrar, srv StoplistServer) {
	// If the following call panics, it indicates UnimplementedStoplistServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Stoplist_ServiceDesc, srv)
}

func _Stoplist_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoplistServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stoplist_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoplistServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoplist_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoplistServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stoplist_Remove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoplistServer).Remove(ctx, req.(*RemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoplist_GetStoplist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStoplistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoplistServer).GetStoplist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stoplist_GetStoplist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoplistServer).GetStoplist(ctx, req.(*GetStoplistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Stoplist_Contains_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoplistServer).Contains(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Stoplist_Contains_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoplistServer).Contains(ctx, req.(*ContainsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Stoplist_ServiceDesc is the grpc.ServiceDesc for Stoplist service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Stoplist_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "stoplist.Stoplist",
	HandlerType: (*StoplistServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _Stoplist_Add_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Stoplist_Remove_Handler,
		},
		{
			MethodName: "GetStoplist",
			Handler:    _Stoplist_GetStoplist_Handler,
		},
		{
			MethodName: "Contains",
			Handler:    _Stoplist_Contains_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/stoplist.proto",
}
